//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByteartRetailMini.Web.Services {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDataObject", Namespace="http://schemas.datacontract.org/2004/07/ByteartRetailMini.Application.DataObjects" +
        "")]
    [System.SerializableAttribute()]
    public partial class ProductDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ByteartRetailMini.Web.Services.CategoryDataObject CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsFeaturedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> UnitPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ByteartRetailMini.Web.Services.CategoryDataObject Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsFeatured {
            get {
                return this.IsFeaturedField;
            }
            set {
                if ((this.IsFeaturedField.Equals(value) != true)) {
                    this.IsFeaturedField = value;
                    this.RaisePropertyChanged("IsFeatured");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryDataObject", Namespace="http://schemas.datacontract.org/2004/07/ByteartRetailMini.Application.DataObjects" +
        "")]
    [System.SerializableAttribute()]
    public partial class CategoryDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ByteartRetailMini.Web.Services.ProductDataObject> ProductsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ByteartRetailMini.Web.Services.ProductDataObject> Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategorizationDataObject", Namespace="http://schemas.datacontract.org/2004/07/ByteartRetailMini.Application.DataObjects" +
        "")]
    [System.SerializableAttribute()]
    public partial class CategorizationDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryIDField, value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIDField, value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PageInfo", Namespace="http://schemas.datacontract.org/2004/07/ByteartRetailMini.Infrastructure")]
    [System.SerializableAttribute()]
    public partial class PageInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OrderPropertyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDesc {
            get {
                return this.IsDescField;
            }
            set {
                if ((this.IsDescField.Equals(value) != true)) {
                    this.IsDescField = value;
                    this.RaisePropertyChanged("IsDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderPropertyName {
            get {
                return this.OrderPropertyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderPropertyNameField, value) != true)) {
                    this.OrderPropertyNameField = value;
                    this.RaisePropertyChanged("OrderPropertyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageIndex {
            get {
                return this.PageIndexField;
            }
            set {
                if ((this.PageIndexField.Equals(value) != true)) {
                    this.PageIndexField = value;
                    this.RaisePropertyChanged("PageIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedListOfProductDataObjectUqqArW2s", Namespace="http://schemas.datacontract.org/2004/07/ByteartRetailMini.Infrastructure")]
    [System.SerializableAttribute()]
    public partial class PagedListOfProductDataObjectUqqArW2s : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ByteartRetailMini.Web.Services.ProductDataObject> ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageSizeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TotalCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> TotalPageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ByteartRetailMini.Web.Services.ProductDataObject> Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageIndex {
            get {
                return this.PageIndexField;
            }
            set {
                if ((this.PageIndexField.Equals(value) != true)) {
                    this.PageIndexField = value;
                    this.RaisePropertyChanged("PageIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageSize {
            get {
                return this.PageSizeField;
            }
            set {
                if ((this.PageSizeField.Equals(value) != true)) {
                    this.PageSizeField = value;
                    this.RaisePropertyChanged("PageSize");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TotalCount {
            get {
                return this.TotalCountField;
            }
            set {
                if ((this.TotalCountField.Equals(value) != true)) {
                    this.TotalCountField = value;
                    this.RaisePropertyChanged("TotalCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> TotalPage {
            get {
                return this.TotalPageField;
            }
            set {
                if ((this.TotalPageField.Equals(value) != true)) {
                    this.TotalPageField = value;
                    this.RaisePropertyChanged("TotalPage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShoppingCartDataObject", Namespace="http://schemas.datacontract.org/2004/07/ByteartRetailMini.Application.DataObjects" +
        "")]
    [System.SerializableAttribute()]
    public partial class ShoppingCartDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ByteartRetailMini.Web.Services.ShoppingCartItemDataObject> ItemsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SubtotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIDField, value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ByteartRetailMini.Web.Services.ShoppingCartItemDataObject> Items {
            get {
                return this.ItemsField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemsField, value) != true)) {
                    this.ItemsField = value;
                    this.RaisePropertyChanged("Items");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Subtotal {
            get {
                return this.SubtotalField;
            }
            set {
                if ((this.SubtotalField.Equals(value) != true)) {
                    this.SubtotalField = value;
                    this.RaisePropertyChanged("Subtotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ShoppingCartItemDataObject", Namespace="http://schemas.datacontract.org/2004/07/ByteartRetailMini.Application.DataObjects" +
        "")]
    [System.SerializableAttribute()]
    public partial class ShoppingCartItemDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LineAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ByteartRetailMini.Web.Services.ProductDataObject ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShoppingCartIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LineAmount {
            get {
                return this.LineAmountField;
            }
            set {
                if ((this.LineAmountField.Equals(value) != true)) {
                    this.LineAmountField = value;
                    this.RaisePropertyChanged("LineAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ByteartRetailMini.Web.Services.ProductDataObject Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShoppingCartID {
            get {
                return this.ShoppingCartIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ShoppingCartIDField, value) != true)) {
                    this.ShoppingCartIDField = value;
                    this.RaisePropertyChanged("ShoppingCartID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesOrderDataObject", Namespace="http://schemas.datacontract.org/2004/07/ByteartRetailMini.Application.DataObjects" +
        "")]
    [System.SerializableAttribute()]
    public partial class SalesOrderDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerAddressCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerAddressCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerAddressStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerAddressStreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerAddressZipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateDeliveredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateDispatchedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ByteartRetailMini.Web.Services.SalesLineDataObject> SalesLinesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<ByteartRetailMini.Web.Services.SalesOrderStatus> StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> SubtotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerAddressCity {
            get {
                return this.CustomerAddressCityField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAddressCityField, value) != true)) {
                    this.CustomerAddressCityField = value;
                    this.RaisePropertyChanged("CustomerAddressCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerAddressCountry {
            get {
                return this.CustomerAddressCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAddressCountryField, value) != true)) {
                    this.CustomerAddressCountryField = value;
                    this.RaisePropertyChanged("CustomerAddressCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerAddressState {
            get {
                return this.CustomerAddressStateField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAddressStateField, value) != true)) {
                    this.CustomerAddressStateField = value;
                    this.RaisePropertyChanged("CustomerAddressState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerAddressStreet {
            get {
                return this.CustomerAddressStreetField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAddressStreetField, value) != true)) {
                    this.CustomerAddressStreetField = value;
                    this.RaisePropertyChanged("CustomerAddressStreet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerAddressZip {
            get {
                return this.CustomerAddressZipField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerAddressZipField, value) != true)) {
                    this.CustomerAddressZipField = value;
                    this.RaisePropertyChanged("CustomerAddressZip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerContact {
            get {
                return this.CustomerContactField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerContactField, value) != true)) {
                    this.CustomerContactField = value;
                    this.RaisePropertyChanged("CustomerContact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerEmail {
            get {
                return this.CustomerEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerEmailField, value) != true)) {
                    this.CustomerEmailField = value;
                    this.RaisePropertyChanged("CustomerEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerIDField, value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerPhone {
            get {
                return this.CustomerPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerPhoneField, value) != true)) {
                    this.CustomerPhoneField = value;
                    this.RaisePropertyChanged("CustomerPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateDelivered {
            get {
                return this.DateDeliveredField;
            }
            set {
                if ((this.DateDeliveredField.Equals(value) != true)) {
                    this.DateDeliveredField = value;
                    this.RaisePropertyChanged("DateDelivered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateDispatched {
            get {
                return this.DateDispatchedField;
            }
            set {
                if ((this.DateDispatchedField.Equals(value) != true)) {
                    this.DateDispatchedField = value;
                    this.RaisePropertyChanged("DateDispatched");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ByteartRetailMini.Web.Services.SalesLineDataObject> SalesLines {
            get {
                return this.SalesLinesField;
            }
            set {
                if ((object.ReferenceEquals(this.SalesLinesField, value) != true)) {
                    this.SalesLinesField = value;
                    this.RaisePropertyChanged("SalesLines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<ByteartRetailMini.Web.Services.SalesOrderStatus> Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Subtotal {
            get {
                return this.SubtotalField;
            }
            set {
                if ((this.SubtotalField.Equals(value) != true)) {
                    this.SubtotalField = value;
                    this.RaisePropertyChanged("Subtotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesLineDataObject", Namespace="http://schemas.datacontract.org/2004/07/ByteartRetailMini.Application.DataObjects" +
        "")]
    [System.SerializableAttribute()]
    public partial class SalesLineDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LineAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ByteartRetailMini.Web.Services.ProductDataObject ProductField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SalesOrderIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> LineAmount {
            get {
                return this.LineAmountField;
            }
            set {
                if ((this.LineAmountField.Equals(value) != true)) {
                    this.LineAmountField = value;
                    this.RaisePropertyChanged("LineAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ByteartRetailMini.Web.Services.ProductDataObject Product {
            get {
                return this.ProductField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductField, value) != true)) {
                    this.ProductField = value;
                    this.RaisePropertyChanged("Product");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SalesOrderID {
            get {
                return this.SalesOrderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SalesOrderIDField, value) != true)) {
                    this.SalesOrderIDField = value;
                    this.RaisePropertyChanged("SalesOrderID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalesOrderStatus", Namespace="http://schemas.datacontract.org/2004/07/ByteartRetailMini.Domain.Models")]
    public enum SalesOrderStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Created = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Paid = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Picked = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dispatched = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delivered = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostbackDataObject", Namespace="http://schemas.datacontract.org/2004/07/ByteartRetailMini.Application.DataObjects" +
        "")]
    [System.SerializableAttribute()]
    public partial class PostbackDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLRVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MachineNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServerArchitectureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ServerDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServerOSField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CLRVersion {
            get {
                return this.CLRVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.CLRVersionField, value) != true)) {
                    this.CLRVersionField = value;
                    this.RaisePropertyChanged("CLRVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MachineName {
            get {
                return this.MachineNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MachineNameField, value) != true)) {
                    this.MachineNameField = value;
                    this.RaisePropertyChanged("MachineName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServerArchitecture {
            get {
                return this.ServerArchitectureField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerArchitectureField, value) != true)) {
                    this.ServerArchitectureField = value;
                    this.RaisePropertyChanged("ServerArchitecture");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ServerDateTime {
            get {
                return this.ServerDateTimeField;
            }
            set {
                if ((this.ServerDateTimeField.Equals(value) != true)) {
                    this.ServerDateTimeField = value;
                    this.RaisePropertyChanged("ServerDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServerOS {
            get {
                return this.ServerOSField;
            }
            set {
                if ((object.ReferenceEquals(this.ServerOSField, value) != true)) {
                    this.ServerOSField = value;
                    this.RaisePropertyChanged("ServerOS");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserDataObject", Namespace="http://schemas.datacontract.org/2004/07/ByteartRetailMini.Application.DataObjects" +
        "")]
    [System.SerializableAttribute()]
    public partial class UserDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ByteartRetailMini.Web.Services.AddressDataObject ContactAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateLastLogonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateRegisteredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ByteartRetailMini.Web.Services.AddressDataObject DeliveryAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsDisabledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ByteartRetailMini.Web.Services.RoleDataObject RoleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contact {
            get {
                return this.ContactField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactField, value) != true)) {
                    this.ContactField = value;
                    this.RaisePropertyChanged("Contact");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ByteartRetailMini.Web.Services.AddressDataObject ContactAddress {
            get {
                return this.ContactAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactAddressField, value) != true)) {
                    this.ContactAddressField = value;
                    this.RaisePropertyChanged("ContactAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateLastLogon {
            get {
                return this.DateLastLogonField;
            }
            set {
                if ((this.DateLastLogonField.Equals(value) != true)) {
                    this.DateLastLogonField = value;
                    this.RaisePropertyChanged("DateLastLogon");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateRegistered {
            get {
                return this.DateRegisteredField;
            }
            set {
                if ((this.DateRegisteredField.Equals(value) != true)) {
                    this.DateRegisteredField = value;
                    this.RaisePropertyChanged("DateRegistered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ByteartRetailMini.Web.Services.AddressDataObject DeliveryAddress {
            get {
                return this.DeliveryAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryAddressField, value) != true)) {
                    this.DeliveryAddressField = value;
                    this.RaisePropertyChanged("DeliveryAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsDisabled {
            get {
                return this.IsDisabledField;
            }
            set {
                if ((this.IsDisabledField.Equals(value) != true)) {
                    this.IsDisabledField = value;
                    this.RaisePropertyChanged("IsDisabled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password {
            get {
                return this.PasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.PasswordField, value) != true)) {
                    this.PasswordField = value;
                    this.RaisePropertyChanged("Password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ByteartRetailMini.Web.Services.RoleDataObject Role {
            get {
                return this.RoleField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleField, value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressDataObject", Namespace="http://schemas.datacontract.org/2004/07/ByteartRetailMini.Application.DataObjects" +
        "")]
    [System.SerializableAttribute()]
    public partial class AddressDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoleDataObject", Namespace="http://schemas.datacontract.org/2004/07/ByteartRetailMini.Application.DataObjects" +
        "")]
    [System.SerializableAttribute()]
    public partial class RoleDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="zhww@outlook.com", ConfigurationName="Services.ProductService")]
    public interface ProductService {
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/CreateProducts", ReplyAction="zhww@outlook.com/ProductService/CreateProductsResponse")]
        System.Collections.Generic.List<ByteartRetailMini.Web.Services.ProductDataObject> CreateProducts(System.Collections.Generic.List<ByteartRetailMini.Web.Services.ProductDataObject> productDataObjects);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/CreateCategories", ReplyAction="zhww@outlook.com/ProductService/CreateCategoriesResponse")]
        System.Collections.Generic.List<ByteartRetailMini.Web.Services.CategoryDataObject> CreateCategories(System.Collections.Generic.List<ByteartRetailMini.Web.Services.CategoryDataObject> categoryDataObjects);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/UpdateProducts", ReplyAction="zhww@outlook.com/ProductService/UpdateProductsResponse")]
        System.Collections.Generic.List<ByteartRetailMini.Web.Services.ProductDataObject> UpdateProducts(System.Collections.Generic.List<ByteartRetailMini.Web.Services.ProductDataObject> productDataObjects);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/UpdateCategories", ReplyAction="zhww@outlook.com/ProductService/UpdateCategoriesResponse")]
        System.Collections.Generic.List<ByteartRetailMini.Web.Services.CategoryDataObject> UpdateCategories(System.Collections.Generic.List<ByteartRetailMini.Web.Services.CategoryDataObject> categoryDataObjects);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/DeleteProducts", ReplyAction="zhww@outlook.com/ProductService/DeleteProductsResponse")]
        void DeleteProducts(System.Collections.Generic.List<int> productIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/DeleteCategories", ReplyAction="zhww@outlook.com/ProductService/DeleteCategoriesResponse")]
        void DeleteCategories(System.Collections.Generic.List<int> categoryIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/CategorizeProduct", ReplyAction="zhww@outlook.com/ProductService/CategorizeProductResponse")]
        ByteartRetailMini.Web.Services.CategorizationDataObject CategorizeProduct(int productID, int categoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/UncategorizeProduct", ReplyAction="zhww@outlook.com/ProductService/UncategorizeProductResponse")]
        void UncategorizeProduct(int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/GetCategoryByID", ReplyAction="zhww@outlook.com/ProductService/GetCategoryByIDResponse")]
        ByteartRetailMini.Web.Services.CategoryDataObject GetCategoryByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/GetCategories", ReplyAction="zhww@outlook.com/ProductService/GetCategoriesResponse")]
        System.Collections.Generic.List<ByteartRetailMini.Web.Services.CategoryDataObject> GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/GetProductByID", ReplyAction="zhww@outlook.com/ProductService/GetProductByIDResponse")]
        ByteartRetailMini.Web.Services.ProductDataObject GetProductByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/GetProducts", ReplyAction="zhww@outlook.com/ProductService/GetProductsResponse")]
        System.Collections.Generic.List<ByteartRetailMini.Web.Services.ProductDataObject> GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/GetProductsWithPagination", ReplyAction="zhww@outlook.com/ProductService/GetProductsWithPaginationResponse")]
        ByteartRetailMini.Web.Services.PagedListOfProductDataObjectUqqArW2s GetProductsWithPagination(ByteartRetailMini.Web.Services.PageInfo pageInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/GetProductsForCategory", ReplyAction="zhww@outlook.com/ProductService/GetProductsForCategoryResponse")]
        System.Collections.Generic.List<ByteartRetailMini.Web.Services.ProductDataObject> GetProductsForCategory(int categoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/GetProductsForCategoryWithPagination", ReplyAction="zhww@outlook.com/ProductService/GetProductsForCategoryWithPaginationResponse")]
        ByteartRetailMini.Web.Services.PagedListOfProductDataObjectUqqArW2s GetProductsForCategoryWithPagination(int categoryID, ByteartRetailMini.Web.Services.PageInfo pageInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/GetFeaturedProducts", ReplyAction="zhww@outlook.com/ProductService/GetFeaturedProductsResponse")]
        System.Collections.Generic.List<ByteartRetailMini.Web.Services.ProductDataObject> GetFeaturedProducts(int count);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductServiceChannel : ByteartRetailMini.Web.Services.ProductService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceClient : System.ServiceModel.ClientBase<ByteartRetailMini.Web.Services.ProductService>, ByteartRetailMini.Web.Services.ProductService {
        
        public ProductServiceClient() {
        }
        
        public ProductServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<ByteartRetailMini.Web.Services.ProductDataObject> CreateProducts(System.Collections.Generic.List<ByteartRetailMini.Web.Services.ProductDataObject> productDataObjects) {
            return base.Channel.CreateProducts(productDataObjects);
        }
        
        public System.Collections.Generic.List<ByteartRetailMini.Web.Services.CategoryDataObject> CreateCategories(System.Collections.Generic.List<ByteartRetailMini.Web.Services.CategoryDataObject> categoryDataObjects) {
            return base.Channel.CreateCategories(categoryDataObjects);
        }
        
        public System.Collections.Generic.List<ByteartRetailMini.Web.Services.ProductDataObject> UpdateProducts(System.Collections.Generic.List<ByteartRetailMini.Web.Services.ProductDataObject> productDataObjects) {
            return base.Channel.UpdateProducts(productDataObjects);
        }
        
        public System.Collections.Generic.List<ByteartRetailMini.Web.Services.CategoryDataObject> UpdateCategories(System.Collections.Generic.List<ByteartRetailMini.Web.Services.CategoryDataObject> categoryDataObjects) {
            return base.Channel.UpdateCategories(categoryDataObjects);
        }
        
        public void DeleteProducts(System.Collections.Generic.List<int> productIDs) {
            base.Channel.DeleteProducts(productIDs);
        }
        
        public void DeleteCategories(System.Collections.Generic.List<int> categoryIDs) {
            base.Channel.DeleteCategories(categoryIDs);
        }
        
        public ByteartRetailMini.Web.Services.CategorizationDataObject CategorizeProduct(int productID, int categoryID) {
            return base.Channel.CategorizeProduct(productID, categoryID);
        }
        
        public void UncategorizeProduct(int productID) {
            base.Channel.UncategorizeProduct(productID);
        }
        
        public ByteartRetailMini.Web.Services.CategoryDataObject GetCategoryByID(int id) {
            return base.Channel.GetCategoryByID(id);
        }
        
        public System.Collections.Generic.List<ByteartRetailMini.Web.Services.CategoryDataObject> GetCategories() {
            return base.Channel.GetCategories();
        }
        
        public ByteartRetailMini.Web.Services.ProductDataObject GetProductByID(int id) {
            return base.Channel.GetProductByID(id);
        }
        
        public System.Collections.Generic.List<ByteartRetailMini.Web.Services.ProductDataObject> GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public ByteartRetailMini.Web.Services.PagedListOfProductDataObjectUqqArW2s GetProductsWithPagination(ByteartRetailMini.Web.Services.PageInfo pageInfo) {
            return base.Channel.GetProductsWithPagination(pageInfo);
        }
        
        public System.Collections.Generic.List<ByteartRetailMini.Web.Services.ProductDataObject> GetProductsForCategory(int categoryID) {
            return base.Channel.GetProductsForCategory(categoryID);
        }
        
        public ByteartRetailMini.Web.Services.PagedListOfProductDataObjectUqqArW2s GetProductsForCategoryWithPagination(int categoryID, ByteartRetailMini.Web.Services.PageInfo pageInfo) {
            return base.Channel.GetProductsForCategoryWithPagination(categoryID, pageInfo);
        }
        
        public System.Collections.Generic.List<ByteartRetailMini.Web.Services.ProductDataObject> GetFeaturedProducts(int count) {
            return base.Channel.GetFeaturedProducts(count);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="zhww@outlook.com", ConfigurationName="Services.OrderService")]
    public interface OrderService {
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/OrderService/GetShoppingCartItemCount", ReplyAction="zhww@outlook.com/OrderService/GetShoppingCartItemCountResponse")]
        int GetShoppingCartItemCount(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/OrderService/AddProductToCart", ReplyAction="zhww@outlook.com/OrderService/AddProductToCartResponse")]
        void AddProductToCart(string userName, int productID, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/OrderService/GetShoppingCart", ReplyAction="zhww@outlook.com/OrderService/GetShoppingCartResponse")]
        ByteartRetailMini.Web.Services.ShoppingCartDataObject GetShoppingCart(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/OrderService/UpdateShoppingCartItem", ReplyAction="zhww@outlook.com/OrderService/UpdateShoppingCartItemResponse")]
        void UpdateShoppingCartItem(int shoppingCartItemID, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/OrderService/DeleteShoppingCartItem", ReplyAction="zhww@outlook.com/OrderService/DeleteShoppingCartItemResponse")]
        void DeleteShoppingCartItem(int shoppingCartItemID);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/OrderService/Checkout", ReplyAction="zhww@outlook.com/OrderService/CheckoutResponse")]
        ByteartRetailMini.Web.Services.SalesOrderDataObject Checkout(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/OrderService/Confirm", ReplyAction="zhww@outlook.com/OrderService/ConfirmResponse")]
        void Confirm(int orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/OrderService/Dispatch", ReplyAction="zhww@outlook.com/OrderService/DispatchResponse")]
        void Dispatch(int orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/OrderService/GetSalesOrdersForUser", ReplyAction="zhww@outlook.com/OrderService/GetSalesOrdersForUserResponse")]
        System.Collections.Generic.List<ByteartRetailMini.Web.Services.SalesOrderDataObject> GetSalesOrdersForUser(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/OrderService/GetAllSalesOrders", ReplyAction="zhww@outlook.com/OrderService/GetAllSalesOrdersResponse")]
        System.Collections.Generic.List<ByteartRetailMini.Web.Services.SalesOrderDataObject> GetAllSalesOrders();
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/OrderService/GetSalesOrder", ReplyAction="zhww@outlook.com/OrderService/GetSalesOrderResponse")]
        ByteartRetailMini.Web.Services.SalesOrderDataObject GetSalesOrder(int orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/OrderService/Test", ReplyAction="zhww@outlook.com/OrderService/TestResponse")]
        void Test();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrderServiceChannel : ByteartRetailMini.Web.Services.OrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderServiceClient : System.ServiceModel.ClientBase<ByteartRetailMini.Web.Services.OrderService>, ByteartRetailMini.Web.Services.OrderService {
        
        public OrderServiceClient() {
        }
        
        public OrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetShoppingCartItemCount(string userName) {
            return base.Channel.GetShoppingCartItemCount(userName);
        }
        
        public void AddProductToCart(string userName, int productID, int quantity) {
            base.Channel.AddProductToCart(userName, productID, quantity);
        }
        
        public ByteartRetailMini.Web.Services.ShoppingCartDataObject GetShoppingCart(string userName) {
            return base.Channel.GetShoppingCart(userName);
        }
        
        public void UpdateShoppingCartItem(int shoppingCartItemID, int quantity) {
            base.Channel.UpdateShoppingCartItem(shoppingCartItemID, quantity);
        }
        
        public void DeleteShoppingCartItem(int shoppingCartItemID) {
            base.Channel.DeleteShoppingCartItem(shoppingCartItemID);
        }
        
        public ByteartRetailMini.Web.Services.SalesOrderDataObject Checkout(string userName) {
            return base.Channel.Checkout(userName);
        }
        
        public void Confirm(int orderID) {
            base.Channel.Confirm(orderID);
        }
        
        public void Dispatch(int orderID) {
            base.Channel.Dispatch(orderID);
        }
        
        public System.Collections.Generic.List<ByteartRetailMini.Web.Services.SalesOrderDataObject> GetSalesOrdersForUser(int userID) {
            return base.Channel.GetSalesOrdersForUser(userID);
        }
        
        public System.Collections.Generic.List<ByteartRetailMini.Web.Services.SalesOrderDataObject> GetAllSalesOrders() {
            return base.Channel.GetAllSalesOrders();
        }
        
        public ByteartRetailMini.Web.Services.SalesOrderDataObject GetSalesOrder(int orderID) {
            return base.Channel.GetSalesOrder(orderID);
        }
        
        public void Test() {
            base.Channel.Test();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="zhww@outlook.com", ConfigurationName="Services.PostbackService")]
    public interface PostbackService {
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/PostbackService/GetPostback", ReplyAction="zhww@outlook.com/PostbackService/GetPostbackResponse")]
        ByteartRetailMini.Web.Services.PostbackDataObject GetPostback();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PostbackServiceChannel : ByteartRetailMini.Web.Services.PostbackService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PostbackServiceClient : System.ServiceModel.ClientBase<ByteartRetailMini.Web.Services.PostbackService>, ByteartRetailMini.Web.Services.PostbackService {
        
        public PostbackServiceClient() {
        }
        
        public PostbackServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PostbackServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostbackServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostbackServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ByteartRetailMini.Web.Services.PostbackDataObject GetPostback() {
            return base.Channel.GetPostback();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="zhww@outlook.com", ConfigurationName="Services.UserService")]
    public interface UserService {
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/UserService/CreateUsers", ReplyAction="zhww@outlook.com/UserService/CreateUsersResponse")]
        System.Collections.Generic.List<ByteartRetailMini.Web.Services.UserDataObject> CreateUsers(System.Collections.Generic.List<ByteartRetailMini.Web.Services.UserDataObject> userDataObjects);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/UserService/ValidateUser", ReplyAction="zhww@outlook.com/UserService/ValidateUserResponse")]
        bool ValidateUser(string userName, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/UserService/DisableUser", ReplyAction="zhww@outlook.com/UserService/DisableUserResponse")]
        bool DisableUser(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/UserService/EnableUser", ReplyAction="zhww@outlook.com/UserService/EnableUserResponse")]
        bool EnableUser(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/UserService/UpdateUsers", ReplyAction="zhww@outlook.com/UserService/UpdateUsersResponse")]
        System.Collections.Generic.List<ByteartRetailMini.Web.Services.UserDataObject> UpdateUsers(System.Collections.Generic.List<ByteartRetailMini.Web.Services.UserDataObject> userDataObjects);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/UserService/DeleteUsers", ReplyAction="zhww@outlook.com/UserService/DeleteUsersResponse")]
        void DeleteUsers(System.Collections.Generic.List<int> userIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/UserService/GetUserByKey", ReplyAction="zhww@outlook.com/UserService/GetUserByKeyResponse")]
        ByteartRetailMini.Web.Services.UserDataObject GetUserByKey(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/UserService/GetUserByEmail", ReplyAction="zhww@outlook.com/UserService/GetUserByEmailResponse")]
        ByteartRetailMini.Web.Services.UserDataObject GetUserByEmail(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/UserService/GetUserByName", ReplyAction="zhww@outlook.com/UserService/GetUserByNameResponse")]
        ByteartRetailMini.Web.Services.UserDataObject GetUserByName(string userName);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/UserService/GetUsers", ReplyAction="zhww@outlook.com/UserService/GetUsersResponse")]
        System.Collections.Generic.List<ByteartRetailMini.Web.Services.UserDataObject> GetUsers();
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/UserService/GetRoles", ReplyAction="zhww@outlook.com/UserService/GetRolesResponse")]
        System.Collections.Generic.List<ByteartRetailMini.Web.Services.RoleDataObject> GetRoles();
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/UserService/GetRoleByKey", ReplyAction="zhww@outlook.com/UserService/GetRoleByKeyResponse")]
        ByteartRetailMini.Web.Services.RoleDataObject GetRoleByKey(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/UserService/CreateRoles", ReplyAction="zhww@outlook.com/UserService/CreateRolesResponse")]
        System.Collections.Generic.List<ByteartRetailMini.Web.Services.RoleDataObject> CreateRoles(System.Collections.Generic.List<ByteartRetailMini.Web.Services.RoleDataObject> roleDataObjects);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/UserService/UpdateRoles", ReplyAction="zhww@outlook.com/UserService/UpdateRolesResponse")]
        System.Collections.Generic.List<ByteartRetailMini.Web.Services.RoleDataObject> UpdateRoles(System.Collections.Generic.List<ByteartRetailMini.Web.Services.RoleDataObject> roleDataObjects);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/UserService/DeleteRoles", ReplyAction="zhww@outlook.com/UserService/DeleteRolesResponse")]
        void DeleteRoles(System.Collections.Generic.List<int> roleIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/UserService/AssignRole", ReplyAction="zhww@outlook.com/UserService/AssignRoleResponse")]
        void AssignRole(int userID, int roleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/UserService/UnassignRole", ReplyAction="zhww@outlook.com/UserService/UnassignRoleResponse")]
        void UnassignRole(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/UserService/GetUserRole", ReplyAction="zhww@outlook.com/UserService/GetUserRoleResponse")]
        ByteartRetailMini.Web.Services.RoleDataObject GetUserRole(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserServiceChannel : ByteartRetailMini.Web.Services.UserService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServiceClient : System.ServiceModel.ClientBase<ByteartRetailMini.Web.Services.UserService>, ByteartRetailMini.Web.Services.UserService {
        
        public UserServiceClient() {
        }
        
        public UserServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<ByteartRetailMini.Web.Services.UserDataObject> CreateUsers(System.Collections.Generic.List<ByteartRetailMini.Web.Services.UserDataObject> userDataObjects) {
            return base.Channel.CreateUsers(userDataObjects);
        }
        
        public bool ValidateUser(string userName, string password) {
            return base.Channel.ValidateUser(userName, password);
        }
        
        public bool DisableUser(int userID) {
            return base.Channel.DisableUser(userID);
        }
        
        public bool EnableUser(int userID) {
            return base.Channel.EnableUser(userID);
        }
        
        public System.Collections.Generic.List<ByteartRetailMini.Web.Services.UserDataObject> UpdateUsers(System.Collections.Generic.List<ByteartRetailMini.Web.Services.UserDataObject> userDataObjects) {
            return base.Channel.UpdateUsers(userDataObjects);
        }
        
        public void DeleteUsers(System.Collections.Generic.List<int> userIDs) {
            base.Channel.DeleteUsers(userIDs);
        }
        
        public ByteartRetailMini.Web.Services.UserDataObject GetUserByKey(int id) {
            return base.Channel.GetUserByKey(id);
        }
        
        public ByteartRetailMini.Web.Services.UserDataObject GetUserByEmail(string email) {
            return base.Channel.GetUserByEmail(email);
        }
        
        public ByteartRetailMini.Web.Services.UserDataObject GetUserByName(string userName) {
            return base.Channel.GetUserByName(userName);
        }
        
        public System.Collections.Generic.List<ByteartRetailMini.Web.Services.UserDataObject> GetUsers() {
            return base.Channel.GetUsers();
        }
        
        public System.Collections.Generic.List<ByteartRetailMini.Web.Services.RoleDataObject> GetRoles() {
            return base.Channel.GetRoles();
        }
        
        public ByteartRetailMini.Web.Services.RoleDataObject GetRoleByKey(int id) {
            return base.Channel.GetRoleByKey(id);
        }
        
        public System.Collections.Generic.List<ByteartRetailMini.Web.Services.RoleDataObject> CreateRoles(System.Collections.Generic.List<ByteartRetailMini.Web.Services.RoleDataObject> roleDataObjects) {
            return base.Channel.CreateRoles(roleDataObjects);
        }
        
        public System.Collections.Generic.List<ByteartRetailMini.Web.Services.RoleDataObject> UpdateRoles(System.Collections.Generic.List<ByteartRetailMini.Web.Services.RoleDataObject> roleDataObjects) {
            return base.Channel.UpdateRoles(roleDataObjects);
        }
        
        public void DeleteRoles(System.Collections.Generic.List<int> roleIDs) {
            base.Channel.DeleteRoles(roleIDs);
        }
        
        public void AssignRole(int userID, int roleID) {
            base.Channel.AssignRole(userID, roleID);
        }
        
        public void UnassignRole(int userID) {
            base.Channel.UnassignRole(userID);
        }
        
        public ByteartRetailMini.Web.Services.RoleDataObject GetUserRole(string name) {
            return base.Channel.GetUserRole(name);
        }
    }
}
