//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34003
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ByteartRetailMini.Web.ProductService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDataObject", Namespace="http://schemas.datacontract.org/2004/07/ByteartRetailMini.Application.DataObjects" +
        "")]
    [System.SerializableAttribute()]
    public partial class ProductDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ByteartRetailMini.Web.ProductService.CategoryDataObject CategoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ImageUrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsFeaturedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> UnitPriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ByteartRetailMini.Web.ProductService.CategoryDataObject Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImageUrl {
            get {
                return this.ImageUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageUrlField, value) != true)) {
                    this.ImageUrlField = value;
                    this.RaisePropertyChanged("ImageUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsFeatured {
            get {
                return this.IsFeaturedField;
            }
            set {
                if ((this.IsFeaturedField.Equals(value) != true)) {
                    this.IsFeaturedField = value;
                    this.RaisePropertyChanged("IsFeatured");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> UnitPrice {
            get {
                return this.UnitPriceField;
            }
            set {
                if ((this.UnitPriceField.Equals(value) != true)) {
                    this.UnitPriceField = value;
                    this.RaisePropertyChanged("UnitPrice");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategoryDataObject", Namespace="http://schemas.datacontract.org/2004/07/ByteartRetailMini.Application.DataObjects" +
        "")]
    [System.SerializableAttribute()]
    public partial class CategoryDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<ByteartRetailMini.Web.ProductService.ProductDataObject> ProductsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ByteartRetailMini.Web.ProductService.ProductDataObject> Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CategorizationDataObject", Namespace="http://schemas.datacontract.org/2004/07/ByteartRetailMini.Application.DataObjects" +
        "")]
    [System.SerializableAttribute()]
    public partial class CategorizationDataObject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CategoryIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryID {
            get {
                return this.CategoryIDField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryIDField, value) != true)) {
                    this.CategoryIDField = value;
                    this.RaisePropertyChanged("CategoryID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductID {
            get {
                return this.ProductIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductIDField, value) != true)) {
                    this.ProductIDField = value;
                    this.RaisePropertyChanged("ProductID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PageInfo", Namespace="http://schemas.datacontract.org/2004/07/ByteartRetailMini.Infrastructure")]
    [System.SerializableAttribute()]
    public partial class PageInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool IsDesck__BackingFieldField;
        
        private string OrderPropertyNamek__BackingFieldField;
        
        private int PageIndexk__BackingFieldField;
        
        private int PageSizek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<IsDesc>k__BackingField", IsRequired=true)]
        public bool IsDesck__BackingField {
            get {
                return this.IsDesck__BackingFieldField;
            }
            set {
                if ((this.IsDesck__BackingFieldField.Equals(value) != true)) {
                    this.IsDesck__BackingFieldField = value;
                    this.RaisePropertyChanged("IsDesck__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<OrderPropertyName>k__BackingField", IsRequired=true)]
        public string OrderPropertyNamek__BackingField {
            get {
                return this.OrderPropertyNamek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.OrderPropertyNamek__BackingFieldField, value) != true)) {
                    this.OrderPropertyNamek__BackingFieldField = value;
                    this.RaisePropertyChanged("OrderPropertyNamek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PageIndex>k__BackingField", IsRequired=true)]
        public int PageIndexk__BackingField {
            get {
                return this.PageIndexk__BackingFieldField;
            }
            set {
                if ((this.PageIndexk__BackingFieldField.Equals(value) != true)) {
                    this.PageIndexk__BackingFieldField = value;
                    this.RaisePropertyChanged("PageIndexk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PageSize>k__BackingField", IsRequired=true)]
        public int PageSizek__BackingField {
            get {
                return this.PageSizek__BackingFieldField;
            }
            set {
                if ((this.PageSizek__BackingFieldField.Equals(value) != true)) {
                    this.PageSizek__BackingFieldField = value;
                    this.RaisePropertyChanged("PageSizek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PagedListOfProductDataObjectUqqArW2s", Namespace="http://schemas.datacontract.org/2004/07/ByteartRetailMini.Infrastructure")]
    [System.SerializableAttribute()]
    public partial class PagedListOfProductDataObjectUqqArW2s : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Collections.Generic.List<ByteartRetailMini.Web.ProductService.ProductDataObject> Itemsk__BackingFieldField;
        
        private int PageIndexk__BackingFieldField;
        
        private int PageSizek__BackingFieldField;
        
        private System.Nullable<int> TotalCountk__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Items>k__BackingField", IsRequired=true)]
        public System.Collections.Generic.List<ByteartRetailMini.Web.ProductService.ProductDataObject> Itemsk__BackingField {
            get {
                return this.Itemsk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Itemsk__BackingFieldField, value) != true)) {
                    this.Itemsk__BackingFieldField = value;
                    this.RaisePropertyChanged("Itemsk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PageIndex>k__BackingField", IsRequired=true)]
        public int PageIndexk__BackingField {
            get {
                return this.PageIndexk__BackingFieldField;
            }
            set {
                if ((this.PageIndexk__BackingFieldField.Equals(value) != true)) {
                    this.PageIndexk__BackingFieldField = value;
                    this.RaisePropertyChanged("PageIndexk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<PageSize>k__BackingField", IsRequired=true)]
        public int PageSizek__BackingField {
            get {
                return this.PageSizek__BackingFieldField;
            }
            set {
                if ((this.PageSizek__BackingFieldField.Equals(value) != true)) {
                    this.PageSizek__BackingFieldField = value;
                    this.RaisePropertyChanged("PageSizek__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<TotalCount>k__BackingField", IsRequired=true)]
        public System.Nullable<int> TotalCountk__BackingField {
            get {
                return this.TotalCountk__BackingFieldField;
            }
            set {
                if ((this.TotalCountk__BackingFieldField.Equals(value) != true)) {
                    this.TotalCountk__BackingFieldField = value;
                    this.RaisePropertyChanged("TotalCountk__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="zhww@outlook.com", ConfigurationName="ProductService.ProductService")]
    public interface ProductService {
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/CreateProducts", ReplyAction="zhww@outlook.com/ProductService/CreateProductsResponse")]
        System.Collections.Generic.List<ByteartRetailMini.Web.ProductService.ProductDataObject> CreateProducts(System.Collections.Generic.List<ByteartRetailMini.Web.ProductService.ProductDataObject> productDataObjects);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/CreateCategories", ReplyAction="zhww@outlook.com/ProductService/CreateCategoriesResponse")]
        System.Collections.Generic.List<ByteartRetailMini.Web.ProductService.CategoryDataObject> CreateCategories(System.Collections.Generic.List<ByteartRetailMini.Web.ProductService.CategoryDataObject> categoryDataObjects);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/UpdateProducts", ReplyAction="zhww@outlook.com/ProductService/UpdateProductsResponse")]
        System.Collections.Generic.List<ByteartRetailMini.Web.ProductService.ProductDataObject> UpdateProducts(System.Collections.Generic.List<ByteartRetailMini.Web.ProductService.ProductDataObject> productDataObjects);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/UpdateCategories", ReplyAction="zhww@outlook.com/ProductService/UpdateCategoriesResponse")]
        System.Collections.Generic.List<ByteartRetailMini.Web.ProductService.CategoryDataObject> UpdateCategories(System.Collections.Generic.List<ByteartRetailMini.Web.ProductService.CategoryDataObject> categoryDataObjects);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/DeleteProducts", ReplyAction="zhww@outlook.com/ProductService/DeleteProductsResponse")]
        void DeleteProducts(System.Collections.Generic.List<string> productIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/DeleteCategories", ReplyAction="zhww@outlook.com/ProductService/DeleteCategoriesResponse")]
        void DeleteCategories(System.Collections.Generic.List<string> categoryIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/CategorizeProduct", ReplyAction="zhww@outlook.com/ProductService/CategorizeProductResponse")]
        ByteartRetailMini.Web.ProductService.CategorizationDataObject CategorizeProduct(System.Guid productID, System.Guid categoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/UncategorizeProduct", ReplyAction="zhww@outlook.com/ProductService/UncategorizeProductResponse")]
        void UncategorizeProduct(System.Guid productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/GetCategoryByID", ReplyAction="zhww@outlook.com/ProductService/GetCategoryByIDResponse")]
        ByteartRetailMini.Web.ProductService.CategoryDataObject GetCategoryByID(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/GetCategories", ReplyAction="zhww@outlook.com/ProductService/GetCategoriesResponse")]
        System.Collections.Generic.List<ByteartRetailMini.Web.ProductService.CategoryDataObject> GetCategories();
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/GetProductByID", ReplyAction="zhww@outlook.com/ProductService/GetProductByIDResponse")]
        ByteartRetailMini.Web.ProductService.ProductDataObject GetProductByID(System.Guid id);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/GetProducts", ReplyAction="zhww@outlook.com/ProductService/GetProductsResponse")]
        System.Collections.Generic.List<ByteartRetailMini.Web.ProductService.ProductDataObject> GetProducts();
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/GetProductsWithPagination", ReplyAction="zhww@outlook.com/ProductService/GetProductsWithPaginationResponse")]
        ByteartRetailMini.Web.ProductService.PagedListOfProductDataObjectUqqArW2s GetProductsWithPagination(ByteartRetailMini.Web.ProductService.PageInfo pageInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/GetProductsForCategory", ReplyAction="zhww@outlook.com/ProductService/GetProductsForCategoryResponse")]
        System.Collections.Generic.List<ByteartRetailMini.Web.ProductService.ProductDataObject> GetProductsForCategory(System.Guid categoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/GetProductsForCategoryWithPagination", ReplyAction="zhww@outlook.com/ProductService/GetProductsForCategoryWithPaginationResponse")]
        ByteartRetailMini.Web.ProductService.PagedListOfProductDataObjectUqqArW2s GetProductsForCategoryWithPagination(System.Guid categoryID, ByteartRetailMini.Web.ProductService.PageInfo pageInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="zhww@outlook.com/ProductService/GetFeaturedProducts", ReplyAction="zhww@outlook.com/ProductService/GetFeaturedProductsResponse")]
        System.Collections.Generic.List<ByteartRetailMini.Web.ProductService.ProductDataObject> GetFeaturedProducts(int count);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductServiceChannel : ByteartRetailMini.Web.ProductService.ProductService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductServiceClient : System.ServiceModel.ClientBase<ByteartRetailMini.Web.ProductService.ProductService>, ByteartRetailMini.Web.ProductService.ProductService {
        
        public ProductServiceClient() {
        }
        
        public ProductServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<ByteartRetailMini.Web.ProductService.ProductDataObject> CreateProducts(System.Collections.Generic.List<ByteartRetailMini.Web.ProductService.ProductDataObject> productDataObjects) {
            return base.Channel.CreateProducts(productDataObjects);
        }
        
        public System.Collections.Generic.List<ByteartRetailMini.Web.ProductService.CategoryDataObject> CreateCategories(System.Collections.Generic.List<ByteartRetailMini.Web.ProductService.CategoryDataObject> categoryDataObjects) {
            return base.Channel.CreateCategories(categoryDataObjects);
        }
        
        public System.Collections.Generic.List<ByteartRetailMini.Web.ProductService.ProductDataObject> UpdateProducts(System.Collections.Generic.List<ByteartRetailMini.Web.ProductService.ProductDataObject> productDataObjects) {
            return base.Channel.UpdateProducts(productDataObjects);
        }
        
        public System.Collections.Generic.List<ByteartRetailMini.Web.ProductService.CategoryDataObject> UpdateCategories(System.Collections.Generic.List<ByteartRetailMini.Web.ProductService.CategoryDataObject> categoryDataObjects) {
            return base.Channel.UpdateCategories(categoryDataObjects);
        }
        
        public void DeleteProducts(System.Collections.Generic.List<string> productIDs) {
            base.Channel.DeleteProducts(productIDs);
        }
        
        public void DeleteCategories(System.Collections.Generic.List<string> categoryIDs) {
            base.Channel.DeleteCategories(categoryIDs);
        }
        
        public ByteartRetailMini.Web.ProductService.CategorizationDataObject CategorizeProduct(System.Guid productID, System.Guid categoryID) {
            return base.Channel.CategorizeProduct(productID, categoryID);
        }
        
        public void UncategorizeProduct(System.Guid productID) {
            base.Channel.UncategorizeProduct(productID);
        }
        
        public ByteartRetailMini.Web.ProductService.CategoryDataObject GetCategoryByID(System.Guid id) {
            return base.Channel.GetCategoryByID(id);
        }
        
        public System.Collections.Generic.List<ByteartRetailMini.Web.ProductService.CategoryDataObject> GetCategories() {
            return base.Channel.GetCategories();
        }
        
        public ByteartRetailMini.Web.ProductService.ProductDataObject GetProductByID(System.Guid id) {
            return base.Channel.GetProductByID(id);
        }
        
        public System.Collections.Generic.List<ByteartRetailMini.Web.ProductService.ProductDataObject> GetProducts() {
            return base.Channel.GetProducts();
        }
        
        public ByteartRetailMini.Web.ProductService.PagedListOfProductDataObjectUqqArW2s GetProductsWithPagination(ByteartRetailMini.Web.ProductService.PageInfo pageInfo) {
            return base.Channel.GetProductsWithPagination(pageInfo);
        }
        
        public System.Collections.Generic.List<ByteartRetailMini.Web.ProductService.ProductDataObject> GetProductsForCategory(System.Guid categoryID) {
            return base.Channel.GetProductsForCategory(categoryID);
        }
        
        public ByteartRetailMini.Web.ProductService.PagedListOfProductDataObjectUqqArW2s GetProductsForCategoryWithPagination(System.Guid categoryID, ByteartRetailMini.Web.ProductService.PageInfo pageInfo) {
            return base.Channel.GetProductsForCategoryWithPagination(categoryID, pageInfo);
        }
        
        public System.Collections.Generic.List<ByteartRetailMini.Web.ProductService.ProductDataObject> GetFeaturedProducts(int count) {
            return base.Channel.GetFeaturedProducts(count);
        }
    }
}
